name: DEV - Deploy to Amazon S3 Bucket

# dev 브랜치에 push가 되면 workflow 동작
on:
  push:
    branches: [deploy/prod]

# 환경변수 정의
env:
  # Organization Secrets
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET_NAME: fuseble-production
  BUILD_ENV: prod

jobs:
  # 소스 빌드 및 배포
  build_deploy:
    name: Build Package and Sync with S3 Bucket
    runs-on: ubuntu-latest

    steps:
      # 소스 가져오기
      - name: Checkout
        uses: actions/checkout@v2
      # AWS credentials 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # NPM 설치 및 빌드
      - name: NPM module install and build
        run: |
          yarn
          yarn run build:${{ env.BUILD_ENV }}
          yarn run deploy -b ${{ env.S3_BUCKET_NAME }}