/* eslint-disable */
/**************** DO NOT TOUCH *****************/
/* This file gets generated by 'env:*' scripts */
/***********************************************/

export default {
  NODE_ENV: 'dev',
  API_URL: 'https://reqres.in/api',
};
